version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: products
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=products

  client:
    build:
      context: ./client
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50051

volumes:
  mysql_data:
